argocd_release_name: argocd
argocd_namespace: argocd
argocd_chart_version: 7.7.7
argocd_helm_values:
  server:
    service:
      type: NodePort
      nodePort: 30080
    config:
      anonymous.enabled: "true"
      users.anonymous.enabled: "true"
      server.insecure: "true"
  rbac:
    policy_default: "role:readonly"
